// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxwaopbvzxpnkgfvychh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4d2FvcGJ2enhwbmtnZnZ5Y2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzNjg0NjYsImV4cCI6MjA4ODk0NDQ2Nn0.y-uWuNAkkF_9PDgF7RBmMEcCNniCB_KPAGEy9OjbJ1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});