// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://ugektfuwfdpcmcrqxyzl.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnZWt0ZnV3ZmRwY21jcnF4eXpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwMjE1NzAsImV4cCI6MjA5MTU5NzU3MH0.z6SHI7CZj0mcbzRVzwCvCLIpO4aTmrS2S6SIH-J86Z4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});